# Generated by Django 2.2.19 on 2023-10-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20231006_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmenu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='выберите родительский пункт меню', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childrens', to='menu.ItemMenu'),
        ),
    ]
